apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: java-app
    spec:
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: pvc
      containers:
      - name: container
        image: us-west2-docker.pkg.dev/avid-shape-390123/artifact/dockerimage
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-volume
          mountPath: /app/src/pusuluru_PV_dir
      - name: container2
        image: us-west2-docker.pkg.dev/avid-shape-390123/artifact2/dockerimage2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared-volume
          mountPath: /app/src/pusuluru_PV_dir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: one-service
spec:
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: two
spec:
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
